const state = { posts: [], filtered: [], visible: 6, category: "All", query: "" };
const $ = (id) => document.getElementById(id);
function formatDate(iso){const d=new Date(iso);return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(d)}
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function applyFilters(){const q=state.query.trim().toLowerCase();state.filtered=state.posts.filter(p=>{const cm=state.category==="All"||p.category===state.category;const t=[p.title,p.excerpt,p.category,p.label].join(" ").toLowerCase();return cm&&(!q||t.includes(q))});render()}
function renderHero(post){if(!post)return;$("heroTitle").textContent=post.title;$("heroExcerpt").textContent=post.excerpt;$("heroCategory").textContent=post.category;$("heroTime").textContent=formatDate(post.createdAt);$("heroLink").href=post.instagramUrl;$("heroArt").style.setProperty("--art-a",post.artA);$("heroArt").style.setProperty("--art-b",post.artB);$("breakingText").textContent=post.title}
function renderTrending(){const items=[...state.posts].sort((a,b)=>(b.trending||0)-(a.trending||0)).slice(0,5);$("trendingList").innerHTML=items.map((p,i)=>`<a class="trend-item" href="${escapeHtml(p.instagramUrl)}" target="_blank" rel="noopener noreferrer"><span class="trend-no">0${i+1}</span><span><span class="trend-title">${escapeHtml(p.title)}</span><span class="trend-meta">${escapeHtml(p.category)} • ${formatDate(p.createdAt)}</span></span></a>`).join("")}
function renderFeed(){const visible=state.filtered.slice(0,state.visible);$("feed").innerHTML=visible.map(p=>`<article class="post-card"><div class="post-art" style="--art-a:${escapeHtml(p.artA)};--art-b:${escapeHtml(p.artB)}"><span>${escapeHtml(p.label)}</span></div><div class="post-body"><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.excerpt)}</p><div class="post-meta"><span><span class="tag">#${escapeHtml(p.category.replaceAll(" ",""))}</span> • ${formatDate(p.createdAt)}</span><a class="post-link" href="${escapeHtml(p.instagramUrl)}" target="_blank" rel="noopener noreferrer">View ↗</a></div></div></article>`).join("");$("resultCount").textContent=`${state.filtered.length} post${state.filtered.length===1?"":"s"}`;$("emptyState").classList.toggle("hidden",state.filtered.length!==0);$("loadMoreBtn").classList.toggle("hidden",state.visible>=state.filtered.length||state.filtered.length===0)}
function render(){renderHero(state.filtered[0]||state.posts[0]);renderTrending();renderFeed()}
async function loadPosts(){try{const r=await fetch("data/posts.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.posts=await r.json();state.posts.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));state.filtered=[...state.posts];render()}catch(e){console.error(e);$("breakingText").textContent="Feed could not be loaded.";$("feed").innerHTML='<article class="post-card" style="grid-column:1/-1;padding:22px"><h3>V1 feed error</h3><p>Check data/posts.json.</p></article>'}}
document.querySelectorAll(".cat").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".cat").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.category=b.dataset.category;state.visible=6;applyFilters()}));
$("searchToggle").addEventListener("click",()=>{$("searchWrap").classList.toggle("open");if($("searchWrap").classList.contains("open"))$("searchInput").focus()});
$("menuToggle").addEventListener("click",()=>{document.querySelector(".category-nav").scrollIntoView({behavior:"smooth",block:"nearest"})});
$("searchInput").addEventListener("input",e=>{state.query=e.target.value;state.visible=6;applyFilters()});
$("loadMoreBtn").addEventListener("click",()=>{state.visible+=6;renderFeed()});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
loadPosts();
